"""
simulate people choosing between berkeley spaces, then train on it.

what this does and does not show
--------------------------------
the place features are guessed (sim/fill_annotations.py) and the preferences
are generated by an assumed utility function below. so a good score here is
evidence that the PIPELINE works -- features load, pairs train, the bayesian
head fits, explanations come out sane -- and evidence about nothing else.
it cannot tell you anything about real students, because the "truth" it
recovers is a function i wrote by hand.

it is still worth running before collecting data, for two reasons:
  1. it sizes the study. the accuracy-vs-sessions curve at the bottom says
     roughly how many labels you need before the model beats the baseline.
  2. it catches the failure where the model looks great because it memorised
     users, by scoring held-out users separately from held-out sessions.
"""

import csv, sys, math
from pathlib import Path
import torch
import torch.nn.functional as F

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from model.scnam import SCNAM, Bilinear, PartialSCNAM

torch.manual_seed(0)

FEATURES = ["noise", "noise_var", "daylight", "greenery", "enclosure", "privacy",
            "crowding", "seat_comfort", "talk_ok", "complexity", "thermal"]
TASKS = ["focus", "read", "brainstorm", "socialize", "calm_down", "decompress"]
D, NT = len(FEATURES), len(TASKS)
C = 3 + NT + 2          # arousal, valence, sensory_tolerance + task + 2 traits


# ------------------------------------------------------------------ load places
def load():
    rows = list(csv.DictReader(open(ROOT / "data/annotations_guessed.csv")))
    names = {r["place_id"]: r["name"] for r in csv.DictReader(open(ROOT / "data/places.csv"))}
    f, meta = [], []
    for r in rows:
        g = lambda k: float(r[k])
        st, so, cap = g("seats_total"), g("seats_occupied"), g("capacity")
        crowd = (so / st) if st else min(1.0, g("people_visible") / max(cap, 1))
        n5 = lambda k: (g(k) - 1) / 4          # 1-5 rating -> 0-1
        f.append([
            (g("db_mean") - 30) / 48,
            min(1.0, (g("db_peak") - g("db_mean")) / 25),
            n5("daylight"), n5("greenery"), n5("enclosure"), n5("privacy"),
            min(1.0, crowd), n5("seat_comfort"), n5("talk_ok"),
            n5("complexity"), n5("thermal"),
        ])
        meta.append((names[r["place_id"]], r["slot"]))
    return torch.tensor(f, dtype=torch.float32).clamp(0, 1), meta


# ------------------------------------------------- the assumed human, for now
def utility(ctx, f):
    """
    a hand-written stand-in for how people choose. replace with real choices.
    written to contain the structure the architecture is meant to capture:
    a noise optimum whose LOCATION depends on arousal and on how
    noise-sensitive the person is.
    """
    ar, va, tol = ctx[:, 0], ctx[:, 1], ctx[:, 2]
    task = {t: ctx[:, 3 + i] for i, t in enumerate(TASKS)}
    ns, ex = ctx[:, 3 + NT], ctx[:, 4 + NT]

    mu = 0.55 - 0.30 * ar - 0.25 * ns + 0.18 * (task["socialize"] + task["brainstorm"])
    u = -(2.6 + 2.0 * ns) * (f[:, 0] - mu) ** 2
    u += -(0.5 + 1.1 * ns) * f[:, 1]
    u += (0.35 + 0.5 * (1 - va)) * (-1.7 * (f[:, 2] - 0.72) ** 2 + f[:, 2])
    u += (0.35 + 0.85 * ar) * f[:, 3]
    u += (0.15 + 0.75 * ar - 0.55 * task["brainstorm"]) * f[:, 4]
    u += (0.25 + 1.00 * task["read"] + 0.85 * task["focus"]
          - 0.90 * task["socialize"] - 0.40 * task["brainstorm"]) * f[:, 5]
    u += -(0.30 + 1.40 * ar - 0.60 * ex - 0.50 * tol) * f[:, 6]
    u += (0.30 + 0.75 * task["read"] + 0.60 * task["decompress"]) * f[:, 7]
    u += (-0.70 * task["read"] - 0.55 * task["focus"]
          + 0.95 * task["socialize"] + 0.75 * task["brainstorm"]) * f[:, 8]
    u += -(0.20 + 0.95 * ar - 0.45 * tol) * f[:, 9]
    u += 0.45 * f[:, 10]
    return u


def make_users(n, gen):
    """traits are stable per person: noise sensitivity and extraversion."""
    return torch.rand(n, 2, generator=gen)


def sessions(users, per_user, places, gen, temp=0.30):
    """each session: a state, a task, two candidate place-slots, one choice."""
    n_u = users.shape[0]
    uid = torch.arange(n_u).repeat_interleave(per_user)
    N = uid.shape[0]

    ctx = torch.zeros(N, C)
    ctx[:, :3] = torch.rand(N, 3, generator=gen)
    t = torch.randint(0, NT, (N,), generator=gen)
    ctx[:, 3:3 + NT] = F.one_hot(t, NT).float()
    ctx[:, 3 + NT:] = users[uid]

    ia = torch.randint(0, places.shape[0], (N,), generator=gen)
    ib = torch.randint(0, places.shape[0], (N,), generator=gen)
    fa, fb = places[ia], places[ib]
    gap = utility(ctx, fa) - utility(ctx, fb)
    y = torch.bernoulli(torch.sigmoid(gap / temp), generator=gen)
    return dict(ctx=ctx, fa=fa, fb=fb, y=y, gap=gap, uid=uid)


# ------------------------------------------------------------------- train/eval
def fit(model, tr, va, steps=2500, bs=256, lr=3e-3, wd=1e-3, use_uid=True):
    opt = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=wd)
    N = tr["y"].shape[0]
    best, best_state, patience = 0.0, None, 0
    for s in range(steps):
        i = torch.randint(0, N, (bs,))
        u = tr["uid"][i] if use_uid else None
        d = model(tr["ctx"][i], tr["fa"][i], u) - model(tr["ctx"][i], tr["fb"][i], u)
        loss = F.binary_cross_entropy_with_logits(d, tr["y"][i])
        opt.zero_grad(); loss.backward(); opt.step()
        if s % 100 == 99:
            acc = accuracy(model, va, use_uid=False)
            if acc > best:
                best, best_state, patience = acc, {k: v.clone() for k, v in model.state_dict().items()}, 0
            else:
                patience += 1
                if patience >= 6:
                    break
    if best_state:
        model.load_state_dict(best_state)
    return model


@torch.no_grad()
def accuracy(model, d, use_uid=False, hard=False):
    """
    agreement with the noiseless preference.

    hard=True keeps only CLOSE CALLS. this matters more than it sounds: with
    225 place-slots, two random candidates are usually miles apart in fit, and
    any model gets those right. overall accuracy is therefore dominated by easy
    pairs and saturates near 90% for anything. the close calls are where the
    state-dependent optimum actually decides the answer, so that is the number
    to report -- for the real study too.
    """
    u = d["uid"] if use_uid else None
    pred = model(d["ctx"], d["fa"], u) - model(d["ctx"], d["fb"], u)
    g = d["gap"].abs()
    keep = (g > 0.05) & (g < 0.40) if hard else (g > 0.05)
    return ((pred[keep] > 0) == (d["gap"][keep] > 0)).float().mean().item()


@torch.no_grad()
def bayes_head(model, d, sigma=0.4, prior=1.0):
    X = model.contributions(d["ctx"], d["fa"]) - model.contributions(d["ctx"], d["fb"])
    t = d["y"] * 2 - 1
    A = X.T @ X / sigma ** 2 + torch.eye(model.d) / prior
    S = torch.linalg.inv(A)
    return S @ (X.T @ t) / sigma ** 2, S


@torch.no_grad()
def recommend(model, ctx, places, meta, k=4, ref=384):
    scores = model(ctx.repeat(places.shape[0], 1), places)
    base = model.contributions(ctx.repeat(ref, 1), places[torch.randint(0, places.shape[0], (ref,))]).mean(0)
    top = scores.argsort(descending=True)[:k]
    out = []
    for i in top:
        phi = model.contributions(ctx, places[i:i + 1])[0] - base
        order = phi.abs().argsort(descending=True)[:3]
        out.append((meta[i], (scores[i] - base.sum()).item(),
                    [(FEATURES[j], phi[j].item(), places[i, j].item()) for j in order]))
    return out


def query(arousal, valence, tol, task, ns=.5, ex=.5):
    c = torch.zeros(1, C)
    c[0, 0], c[0, 1], c[0, 2] = arousal, valence, tol
    c[0, 3 + TASKS.index(task)] = 1
    c[0, 3 + NT], c[0, 4 + NT] = ns, ex
    return c


if __name__ == "__main__":
    places, meta = load()
    print(f"{places.shape[0]} place-slots, {places.shape[1]} features\n")

    gen = torch.Generator().manual_seed(7)
    N_USERS, PER = 80, 30
    users = make_users(N_USERS, gen)

    # split BY USER so cold start is measured honestly
    tr_u, te_u = users[:64], users[64:]
    tr_all = sessions(tr_u, PER, places, gen)
    n_tr = int(tr_all["y"].shape[0] * .85)
    tr = {k: v[:n_tr] for k, v in tr_all.items()}
    va = {k: v[n_tr:] for k, v in tr_all.items()}
    te_new = sessions(te_u, PER, places, gen)          # users never seen
    print(f"train {tr['y'].shape[0]} pairs from {len(tr_u)} users")
    print(f"held-out sessions {va['y'].shape[0]} | held-out users {te_new['y'].shape[0]}\n")

    # a free shape function only where theory expects an interior optimum
    FREE = [FEATURES.index("noise"), FEATURES.index("daylight")]

    base = fit(Bilinear(D, C), tr, va, use_uid=False)
    part = fit(PartialSCNAM(D, C, FREE), tr, va, use_uid=False)
    sc = fit(SCNAM(D, C, k=8, n_users=N_USERS), tr, va)
    nparam = lambda m: sum(p.numel() for p in m.parameters())

    print("pairwise accuracy")
    print(f"{'':<12}{'all pairs':>11}{'close calls':>14}{'new users':>12}{'new, close':>13}")
    for nm, m in [("bilinear", base), ("partial", part), ("sc-nam", sc)]:
        print(f"  {nm:<10}{accuracy(m, va)*100:10.1f}%"
              f"{accuracy(m, va, hard=True)*100:13.1f}%"
              f"{accuracy(m, te_new)*100:11.1f}%"
              f"{accuracy(m, te_new, hard=True)*100:12.1f}%")
    n_hard = int(((va["gap"].abs() > .05) & (va["gap"].abs() < .40)).sum())
    print(f"  ({n_hard} of {va['y'].shape[0]} held-out pairs are close calls)")
    print(f"  params: bilinear {nparam(base):,}  partial {nparam(part):,}  "
          f"sc-nam {nparam(sc):,}")

    m, S = bayes_head(sc, tr)
    sd = S.diag().sqrt()
    print(f"\nbayesian head — features the model is least sure about")
    for i in sd.argsort(descending=True)[:3]:
        print(f"  {FEATURES[i]:<13} posterior sd {sd[i]:.3f}")

    print("\n" + "-" * 66)
    demos = [
        ("overstimulated, needs to read for an hour", query(.88, .30, .15, "read", ns=.8)),
        ("flat and drained, needs to start an essay", query(.15, .35, .70, "focus", ns=.3)),
        ("wants to think out loud with a friend",     query(.50, .75, .60, "brainstorm", ex=.8)),
    ]
    best = part
    for label, ctx in demos:
        print(f"\n{label}")
        for (name, slot), score, rows in recommend(best, ctx, places, meta):
            print(f"  {name[:32]:<32} {slot[:12]:<12} fit {score:+.2f}")
            for fn, phi, val in rows:
                bar = ("█" if phi > 0 else "░") * max(1, min(16, int(abs(phi) * 7)))
                print(f"      {fn:<12} obs {val:.2f}  {phi:+.2f} {bar}")

    print("\n" + "-" * 66)
    print("\nhow many labels do you actually need (close calls, new users,")
    print("mean of 3 seeds -- a single seed swings enough to invent a trend)")
    for per in [4, 8, 15, 30]:
        bs_, ps_, ss_ = [], [], []
        for seed in (3, 4, 5):
            g2 = torch.Generator().manual_seed(seed)
            d = sessions(tr_u, per, places, g2)
            n = int(d["y"].shape[0] * .85)
            t2 = {k: v[:n] for k, v in d.items()}; v2 = {k: v[n:] for k, v in d.items()}
            bs_.append(accuracy(fit(Bilinear(D, C), t2, v2, use_uid=False), te_new, hard=True))
            ps_.append(accuracy(fit(PartialSCNAM(D, C, FREE), t2, v2, use_uid=False), te_new, hard=True))
            ss_.append(accuracy(fit(SCNAM(D, C, k=8, n_users=N_USERS), t2, v2), te_new, hard=True))
        mb, mp, ms = sum(bs_)/3, sum(ps_)/3, sum(ss_)/3
        print(f"  {per*len(tr_u):>5} pairs   bilinear {mb*100:5.1f}%   "
              f"partial {mp*100:5.1f}%   sc-nam {ms*100:5.1f}%")
