/* generated by sim/export_web.py — do not edit by hand */
const MODEL_ACC = 0.795;
const PLACES = [
 {
  "id": "p01",
  "name": "doe library main reading room",
  "lat": 37.87229,
  "lng": -122.25931,
  "cat": "quiet",
  "blurb": "long tables, high ceilings, everyone reading in the same direction.",
  "tags": [
   "reading",
   "focus"
  ]
 },
 {
  "id": "p03",
  "name": "morrison library",
  "lat": 37.87205,
  "lng": -122.25902,
  "cat": "enclosed",
  "blurb": "wood panels, lamps, armchairs. no laptops, so no clatter.",
  "tags": [
   "reading",
   "decompress"
  ]
 },
 {
  "id": "p04",
  "name": "main stacks (doe lower level)",
  "lat": 37.87215,
  "lng": -122.25975,
  "cat": "enclosed",
  "blurb": "underground. no daylight at all, and nobody talks.",
  "tags": [
   "focus"
  ]
 },
 {
  "id": "p06",
  "name": "moffitt library 4th floor",
  "lat": 37.87275,
  "lng": -122.26071,
  "cat": "hum",
  "blurb": "steady low buzz. easy to disappear into if you like company nearby.",
  "tags": [
   "focus",
   "company"
  ]
 },
 {
  "id": "p07",
  "name": "east asian library",
  "lat": 37.87352,
  "lng": -122.26018,
  "cat": "quiet",
  "blurb": "wide light, almost no foot traffic past the second floor.",
  "tags": [
   "focus",
   "reading"
  ]
 },
 {
  "id": "p08",
  "name": "bancroft library reading room",
  "lat": 37.87199,
  "lng": -122.25872,
  "cat": "quiet",
  "blurb": "bag check at the door. everything here moves at half speed.",
  "tags": [
   "reading"
  ]
 },
 {
  "id": "p11",
  "name": "free speech movement cafe",
  "lat": 37.87251,
  "lng": -122.26016,
  "cat": "hum",
  "blurb": "talk, espresso, chairs scraping. good when silence feels worse.",
  "tags": [
   "company",
   "brainstorm"
  ]
 },
 {
  "id": "p13",
  "name": "vlsb atrium",
  "lat": 37.8713,
  "lng": -122.2624,
  "cat": "light",
  "blurb": "tall volume under the skeleton. warm and busy in the middle.",
  "tags": [
   "light"
  ]
 },
 {
  "id": "p14",
  "name": "dwinelle hall courtyard",
  "lat": 37.87058,
  "lng": -122.261,
  "cat": "enclosed",
  "blurb": "concrete pocket with benches. loud outside, muffled inside.",
  "tags": [
   "focus"
  ]
 },
 {
  "id": "p15",
  "name": "wheeler hall corridor benches",
  "lat": 37.8702,
  "lng": -122.2589,
  "cat": "enclosed",
  "blurb": "busy between the hour, then completely still.",
  "tags": [
   "focus"
  ]
 },
 {
  "id": "p16",
  "name": "soda hall 5th floor (wozniak lounge)",
  "lat": 37.8756,
  "lng": -122.2589,
  "cat": "light",
  "blurb": "glass corner, long views west, mostly silent after dark.",
  "tags": [
   "focus",
   "light"
  ]
 },
 {
  "id": "p18",
  "name": "hearst mining building lobby",
  "lat": 37.874,
  "lng": -122.25732,
  "cat": "light",
  "blurb": "domed skylights and stone. almost nobody sits here.",
  "tags": [
   "think",
   "light"
  ]
 },
 {
  "id": "p21",
  "name": "kroeber hall courtyard",
  "lat": 37.86985,
  "lng": -122.25565,
  "cat": "enclosed",
  "blurb": "small shaded square, fountain, almost always free seats.",
  "tags": [
   "calm",
   "reading"
  ]
 },
 {
  "id": "p22",
  "name": "memorial glade",
  "lat": 37.87313,
  "lng": -122.25955,
  "cat": "open",
  "blurb": "flat open grass with the whole sky over it.",
  "tags": [
   "decompress",
   "social"
  ]
 },
 {
  "id": "p23",
  "name": "faculty glade",
  "lat": 37.87107,
  "lng": -122.25717,
  "cat": "greenery",
  "blurb": "sunken lawn under old trees, tucked off the main paths.",
  "tags": [
   "calm",
   "decompress"
  ]
 },
 {
  "id": "p24",
  "name": "eucalyptus grove",
  "lat": 37.8702,
  "lng": -122.2619,
  "cat": "greenery",
  "blurb": "tallest hardwoods around. cool, dim, smells like the coast.",
  "tags": [
   "calm",
   "walk"
  ]
 },
 {
  "id": "p25",
  "name": "strawberry creek north fork",
  "lat": 37.8732,
  "lng": -122.26185,
  "cat": "greenery",
  "blurb": "water noise covers everything else. benches along the bank.",
  "tags": [
   "calm",
   "walk"
  ]
 },
 {
  "id": "p26",
  "name": "observatory hill",
  "lat": 37.8743,
  "lng": -122.26055,
  "cat": "greenery",
  "blurb": "a hill nobody crosses on purpose. views west, mostly empty.",
  "tags": [
   "solitude"
  ]
 },
 {
  "id": "p27",
  "name": "south hall lawn",
  "lat": 37.8709,
  "lng": -122.25812,
  "cat": "greenery",
  "blurb": "small lawn behind the oldest building on campus.",
  "tags": [
   "calm"
  ]
 },
 {
  "id": "p30",
  "name": "sather tower esplanade",
  "lat": 37.87216,
  "lng": -122.25783,
  "cat": "open",
  "blurb": "wide stone, long sight lines, bells on the hour.",
  "tags": [
   "walk",
   "think"
  ]
 },
 {
  "id": "p31",
  "name": "hearst mining circle",
  "lat": 37.874,
  "lng": -122.2573,
  "cat": "open",
  "blurb": "a big quiet oval. rarely more than a few people.",
  "tags": [
   "walk",
   "think"
  ]
 },
 {
  "id": "p32",
  "name": "hearst greek theatre",
  "lat": 37.87389,
  "lng": -122.25436,
  "cat": "open",
  "blurb": "empty stone tiers most days. sit high up and the city opens.",
  "tags": [
   "solitude",
   "decompress"
  ]
 },
 {
  "id": "p33",
  "name": "north field",
  "lat": 37.86995,
  "lng": -122.2564,
  "cat": "open",
  "blurb": "turf and fences. quiet outside practice hours.",
  "tags": [
   "decompress"
  ]
 },
 {
  "id": "p34",
  "name": "sproul plaza",
  "lat": 37.8696,
  "lng": -122.2589,
  "cat": "hum",
  "blurb": "the loudest place on campus. tables, flyers, drums.",
  "tags": [
   "social"
  ]
 },
 {
  "id": "p35",
  "name": "lower sproul terrace",
  "lat": 37.8693,
  "lng": -122.2604,
  "cat": "hum",
  "blurb": "open terrace, food, constant crossing traffic.",
  "tags": [
   "social",
   "company"
  ]
 },
 {
  "id": "p37",
  "name": "haas school courtyard",
  "lat": 37.87178,
  "lng": -122.2533,
  "cat": "hum",
  "blurb": "terraced steps, coffee, low conversation all day.",
  "tags": [
   "company",
   "brainstorm"
  ]
 },
 {
  "id": "p38",
  "name": "bowles hall steps",
  "lat": 37.8733,
  "lng": -122.2529,
  "cat": "enclosed",
  "blurb": "east edge of campus, shaded, up against the hill.",
  "tags": [
   "solitude"
  ]
 },
 {
  "id": "p39",
  "name": "foothill terrace",
  "lat": 37.8754,
  "lng": -122.2547,
  "cat": "light",
  "blurb": "uphill, warm brick, quiet in the middle of the day.",
  "tags": [
   "calm",
   "reading"
  ]
 }
];
const QUERIES = [
 {
  "id": "read",
  "prompt": "i am overstimulated and need to read for an hour",
  "reply": "<b>morrison library</b>, weekend midday. it is enclosed, and it is a silent room.",
  "top": "p03",
  "ranked": [
   "p03",
   "p08",
   "p25",
   "p01",
   "p07",
   "p26",
   "p24",
   "p38",
   "p16",
   "p06",
   "p32",
   "p04",
   "p21",
   "p39",
   "p37",
   "p14",
   "p23",
   "p33",
   "p27",
   "p22",
   "p13",
   "p18",
   "p15",
   "p31",
   "p30",
   "p11",
   "p35",
   "p34"
  ],
  "places": {
   "p01": {
    "fit": 6.916,
    "slot": "weekend midday",
    "why": [
     {
      "f": "talk_ok",
      "phi": 1.961,
      "obs": 0.0,
      "text": "it is a silent room"
     },
     {
      "f": "greenery",
      "phi": -1.873,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "enclosure",
      "phi": 1.6,
      "obs": 0.75,
      "text": "it is enclosed"
     },
     {
      "f": "complexity",
      "phi": 1.099,
      "obs": 0.0,
      "text": "there is little to look at"
     }
    ]
   },
   "p03": {
    "fit": 8.897,
    "slot": "weekend midday",
    "why": [
     {
      "f": "enclosure",
      "phi": 2.674,
      "obs": 1.0,
      "text": "it is enclosed"
     },
     {
      "f": "talk_ok",
      "phi": 1.961,
      "obs": 0.0,
      "text": "it is a silent room"
     },
     {
      "f": "greenery",
      "phi": -1.873,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "noise_var",
      "phi": 1.49,
      "obs": 0.24,
      "text": "the sound is steady rather than sudden"
     }
    ]
   },
   "p04": {
    "fit": 4.419,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": -2.598,
      "obs": 0.0,
      "text": "there is no real daylight"
     },
     {
      "f": "talk_ok",
      "phi": 1.961,
      "obs": 0.0,
      "text": "it is a silent room"
     },
     {
      "f": "greenery",
      "phi": -1.873,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "enclosure",
      "phi": 1.6,
      "obs": 0.75,
      "text": "it is enclosed"
     }
    ]
   },
   "p06": {
    "fit": 5.36,
    "slot": "weekend midday",
    "why": [
     {
      "f": "talk_ok",
      "phi": 1.961,
      "obs": 0.0,
      "text": "it is a silent room"
     },
     {
      "f": "greenery",
      "phi": -1.873,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "enclosure",
      "phi": 1.6,
      "obs": 0.75,
      "text": "it is enclosed"
     },
     {
      "f": "complexity",
      "phi": 1.099,
      "obs": 0.0,
      "text": "there is little to look at"
     }
    ]
   },
   "p07": {
    "fit": 6.849,
    "slot": "weekend midday",
    "why": [
     {
      "f": "talk_ok",
      "phi": 1.961,
      "obs": 0.0,
      "text": "it is a silent room"
     },
     {
      "f": "greenery",
      "phi": -1.873,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "enclosure",
      "phi": 1.6,
      "obs": 0.75,
      "text": "it is enclosed"
     },
     {
      "f": "complexity",
      "phi": 1.099,
      "obs": 0.0,
      "text": "there is little to look at"
     }
    ]
   },
   "p08": {
    "fit": 8.316,
    "slot": "weekend midday",
    "why": [
     {
      "f": "talk_ok",
      "phi": 1.961,
      "obs": 0.0,
      "text": "it is a silent room"
     },
     {
      "f": "greenery",
      "phi": -1.873,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "enclosure",
      "phi": 1.6,
      "obs": 0.75,
      "text": "it is enclosed"
     },
     {
      "f": "privacy",
      "phi": 1.439,
      "obs": 1.0,
      "text": "nobody passes behind you"
     }
    ]
   },
   "p11": {
    "fit": -5.106,
    "slot": "weekend midday",
    "why": [
     {
      "f": "noise",
      "phi": -1.71,
      "obs": 0.57,
      "text": "it is loud"
     },
     {
      "f": "talk_ok",
      "phi": -1.5,
      "obs": 1.0,
      "text": "talking is normal there"
     },
     {
      "f": "complexity",
      "phi": -1.17,
      "obs": 0.75,
      "text": "there is a lot competing for attention"
     },
     {
      "f": "noise_var",
      "phi": -1.054,
      "obs": 0.76,
      "text": "the noise comes in bursts"
     }
    ]
   },
   "p13": {
    "fit": 0.969,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.047,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "greenery",
      "phi": -0.792,
      "obs": 0.25,
      "text": "there is nothing green in view"
     },
     {
      "f": "crowding",
      "phi": 0.706,
      "obs": 0.16,
      "text": "it is nearly empty at that hour"
     },
     {
      "f": "noise",
      "phi": 0.566,
      "obs": 0.29,
      "text": "it is quiet"
     }
    ]
   },
   "p14": {
    "fit": 3.568,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.047,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.667,
      "obs": 0.26,
      "text": "it is quiet"
     },
     {
      "f": "privacy",
      "phi": 0.647,
      "obs": 0.75,
      "text": "nobody passes behind you"
     },
     {
      "f": "talk_ok",
      "phi": -0.635,
      "obs": 0.75,
      "text": "talking is normal there"
     }
    ]
   },
   "p15": {
    "fit": -1.48,
    "slot": "weekend midday",
    "why": [
     {
      "f": "greenery",
      "phi": -1.873,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "noise_var",
      "phi": -1.209,
      "obs": 0.8,
      "text": "the noise comes in bursts"
     },
     {
      "f": "noise",
      "phi": 0.942,
      "obs": 0.17,
      "text": "it is quiet"
     },
     {
      "f": "enclosure",
      "phi": 0.525,
      "obs": 0.5,
      "text": "it is open on all sides"
     }
    ]
   },
   "p16": {
    "fit": 5.826,
    "slot": "weekend midday",
    "why": [
     {
      "f": "enclosure",
      "phi": 1.6,
      "obs": 0.75,
      "text": "it is enclosed"
     },
     {
      "f": "privacy",
      "phi": 1.439,
      "obs": 1.0,
      "text": "nobody passes behind you"
     },
     {
      "f": "seat_comfort",
      "phi": 1.294,
      "obs": 1.0,
      "text": "the seating is comfortable for a long sit"
     },
     {
      "f": "daylight",
      "phi": 1.047,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     }
    ]
   },
   "p18": {
    "fit": 0.637,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.047,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "crowding",
      "phi": 0.997,
      "obs": 0.08,
      "text": "it is nearly empty at that hour"
     },
     {
      "f": "noise_var",
      "phi": -0.996,
      "obs": 0.75,
      "text": "the noise comes in bursts"
     },
     {
      "f": "greenery",
      "phi": -0.792,
      "obs": 0.25,
      "text": "there is nothing green in view"
     }
    ]
   },
   "p21": {
    "fit": 4.172,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.047,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.876,
      "obs": 0.2,
      "text": "it is quiet"
     },
     {
      "f": "crowding",
      "phi": 0.743,
      "obs": 0.15,
      "text": "it is nearly empty at that hour"
     },
     {
      "f": "privacy",
      "phi": 0.647,
      "obs": 0.75,
      "text": "nobody passes behind you"
     }
    ]
   },
   "p22": {
    "fit": 1.37,
    "slot": "weekend midday",
    "why": [
     {
      "f": "greenery",
      "phi": 2.45,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "enclosure",
      "phi": -1.624,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "daylight",
      "phi": 1.047,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 1.019,
      "obs": 0.12,
      "text": "it is quiet"
     }
    ]
   },
   "p23": {
    "fit": 3.306,
    "slot": "weekend midday",
    "why": [
     {
      "f": "greenery",
      "phi": 2.45,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "enclosure",
      "phi": -1.624,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "complexity",
      "phi": 1.099,
      "obs": 0.0,
      "text": "there is little to look at"
     },
     {
      "f": "daylight",
      "phi": 1.047,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     }
    ]
   },
   "p24": {
    "fit": 5.982,
    "slot": "weekend midday",
    "why": [
     {
      "f": "greenery",
      "phi": 2.45,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "privacy",
      "phi": 1.439,
      "obs": 1.0,
      "text": "nobody passes behind you"
     },
     {
      "f": "daylight",
      "phi": -1.407,
      "obs": 0.25,
      "text": "there is no real daylight"
     },
     {
      "f": "crowding",
      "phi": 1.287,
      "obs": 0.0,
      "text": "it is nearly empty at that hour"
     }
    ]
   },
   "p25": {
    "fit": 7.277,
    "slot": "weekend midday",
    "why": [
     {
      "f": "greenery",
      "phi": 2.45,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "privacy",
      "phi": 1.439,
      "obs": 1.0,
      "text": "nobody passes behind you"
     },
     {
      "f": "noise_var",
      "phi": 1.218,
      "obs": 0.3,
      "text": "the sound is steady rather than sudden"
     },
     {
      "f": "crowding",
      "phi": 0.924,
      "obs": 0.1,
      "text": "it is nearly empty at that hour"
     }
    ]
   },
   "p26": {
    "fit": 6.794,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "enclosure",
      "phi": -1.624,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "privacy",
      "phi": 1.439,
      "obs": 1.0,
      "text": "nobody passes behind you"
     },
     {
      "f": "greenery",
      "phi": 1.369,
      "obs": 0.75,
      "text": "there is planting in view"
     },
     {
      "f": "crowding",
      "phi": 1.287,
      "obs": 0.0,
      "text": "it is nearly empty at that hour"
     }
    ]
   },
   "p27": {
    "fit": 3.108,
    "slot": "weekend midday",
    "why": [
     {
      "f": "greenery",
      "phi": 2.45,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "enclosure",
      "phi": -1.624,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "complexity",
      "phi": 1.099,
      "obs": 0.0,
      "text": "there is little to look at"
     },
     {
      "f": "daylight",
      "phi": 1.047,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     }
    ]
   },
   "p30": {
    "fit": -4.953,
    "slot": "weekend midday",
    "why": [
     {
      "f": "enclosure",
      "phi": -1.624,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "talk_ok",
      "phi": -1.5,
      "obs": 1.0,
      "text": "talking is normal there"
     },
     {
      "f": "daylight",
      "phi": 1.047,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise_var",
      "phi": -0.976,
      "obs": 0.75,
      "text": "the noise comes in bursts"
     }
    ]
   },
   "p31": {
    "fit": -3.907,
    "slot": "weekend midday",
    "why": [
     {
      "f": "enclosure",
      "phi": -1.624,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "talk_ok",
      "phi": -1.5,
      "obs": 1.0,
      "text": "talking is normal there"
     },
     {
      "f": "daylight",
      "phi": 1.047,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "crowding",
      "phi": 0.985,
      "obs": 0.08,
      "text": "it is nearly empty at that hour"
     }
    ]
   },
   "p32": {
    "fit": 4.801,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "enclosure",
      "phi": -1.624,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "privacy",
      "phi": 1.439,
      "obs": 1.0,
      "text": "nobody passes behind you"
     },
     {
      "f": "complexity",
      "phi": 1.099,
      "obs": 0.0,
      "text": "there is little to look at"
     },
     {
      "f": "daylight",
      "phi": 1.047,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     }
    ]
   },
   "p33": {
    "fit": 3.216,
    "slot": "weekend midday",
    "why": [
     {
      "f": "enclosure",
      "phi": -1.624,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "greenery",
      "phi": 1.369,
      "obs": 0.75,
      "text": "there is planting in view"
     },
     {
      "f": "complexity",
      "phi": 1.099,
      "obs": 0.0,
      "text": "there is little to look at"
     },
     {
      "f": "daylight",
      "phi": 1.047,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     }
    ]
   },
   "p34": {
    "fit": -11.759,
    "slot": "weekend midday",
    "why": [
     {
      "f": "noise",
      "phi": -3.076,
      "obs": 0.68,
      "text": "it is loud"
     },
     {
      "f": "complexity",
      "phi": -1.926,
      "obs": 1.0,
      "text": "there is a lot competing for attention"
     },
     {
      "f": "privacy",
      "phi": -1.727,
      "obs": 0.0,
      "text": "you are exposed to foot traffic"
     },
     {
      "f": "enclosure",
      "phi": -1.624,
      "obs": 0.0,
      "text": "it is open on all sides"
     }
    ]
   },
   "p35": {
    "fit": -9.931,
    "slot": "weekend midday",
    "why": [
     {
      "f": "noise",
      "phi": -2.636,
      "obs": 0.65,
      "text": "it is loud"
     },
     {
      "f": "privacy",
      "phi": -1.727,
      "obs": 0.0,
      "text": "you are exposed to foot traffic"
     },
     {
      "f": "enclosure",
      "phi": -1.624,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "talk_ok",
      "phi": -1.5,
      "obs": 1.0,
      "text": "talking is normal there"
     }
    ]
   },
   "p37": {
    "fit": 3.929,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.047,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.756,
      "obs": 0.24,
      "text": "it is quiet"
     },
     {
      "f": "privacy",
      "phi": 0.647,
      "obs": 0.75,
      "text": "nobody passes behind you"
     },
     {
      "f": "talk_ok",
      "phi": -0.635,
      "obs": 0.75,
      "text": "talking is normal there"
     }
    ]
   },
   "p38": {
    "fit": 5.925,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "privacy",
      "phi": 1.439,
      "obs": 1.0,
      "text": "nobody passes behind you"
     },
     {
      "f": "greenery",
      "phi": 1.369,
      "obs": 0.75,
      "text": "there is planting in view"
     },
     {
      "f": "complexity",
      "phi": 1.099,
      "obs": 0.0,
      "text": "there is little to look at"
     },
     {
      "f": "noise",
      "phi": 0.893,
      "obs": 0.2,
      "text": "it is quiet"
     }
    ]
   },
   "p39": {
    "fit": 4.051,
    "slot": "weekend midday",
    "why": [
     {
      "f": "privacy",
      "phi": 1.439,
      "obs": 1.0,
      "text": "nobody passes behind you"
     },
     {
      "f": "daylight",
      "phi": 1.047,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 1.005,
      "obs": 0.14,
      "text": "it is quiet"
     },
     {
      "f": "talk_ok",
      "phi": -0.635,
      "obs": 0.75,
      "text": "talking is normal there"
     }
    ]
   }
  }
 },
 {
  "id": "focus",
  "prompt": "i feel flat and i have to start an essay",
  "reply": "<b>soda hall 5th floor (wozniak lounge)</b>, weekend midday. the seating is comfortable for a long sit, and there is daylight where you would sit.",
  "top": "p16",
  "ranked": [
   "p16",
   "p25",
   "p08",
   "p03",
   "p26",
   "p01",
   "p07",
   "p38",
   "p39",
   "p37",
   "p21",
   "p14",
   "p32",
   "p27",
   "p23",
   "p24",
   "p33",
   "p06",
   "p22",
   "p13",
   "p18",
   "p11",
   "p04",
   "p31",
   "p30",
   "p15",
   "p35",
   "p34"
  ],
  "places": {
   "p01": {
    "fit": 2.968,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "greenery",
      "phi": -1.225,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "thermal",
      "phi": 1.188,
      "obs": 1.0,
      "text": "it is comfortable to sit in"
     },
     {
      "f": "enclosure",
      "phi": 0.891,
      "obs": 0.75,
      "text": "it is enclosed"
     },
     {
      "f": "talk_ok",
      "phi": 0.669,
      "obs": 0.0,
      "text": "it is a silent room"
     }
    ]
   },
   "p03": {
    "fit": 3.188,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "enclosure",
      "phi": 1.489,
      "obs": 1.0,
      "text": "it is enclosed"
     },
     {
      "f": "daylight",
      "phi": -1.47,
      "obs": 0.25,
      "text": "there is no real daylight"
     },
     {
      "f": "seat_comfort",
      "phi": 1.41,
      "obs": 1.0,
      "text": "the seating is comfortable for a long sit"
     },
     {
      "f": "greenery",
      "phi": -1.225,
      "obs": 0.0,
      "text": "there is nothing green in view"
     }
    ]
   },
   "p04": {
    "fit": -0.307,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "daylight",
      "phi": -2.707,
      "obs": 0.0,
      "text": "there is no real daylight"
     },
     {
      "f": "greenery",
      "phi": -1.225,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "thermal",
      "phi": 1.188,
      "obs": 1.0,
      "text": "it is comfortable to sit in"
     },
     {
      "f": "enclosure",
      "phi": 0.891,
      "obs": 0.75,
      "text": "it is enclosed"
     }
    ]
   },
   "p06": {
    "fit": 1.335,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "greenery",
      "phi": -1.225,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "thermal",
      "phi": 1.188,
      "obs": 1.0,
      "text": "it is comfortable to sit in"
     },
     {
      "f": "enclosure",
      "phi": 0.891,
      "obs": 0.75,
      "text": "it is enclosed"
     },
     {
      "f": "talk_ok",
      "phi": 0.669,
      "obs": 0.0,
      "text": "it is a silent room"
     }
    ]
   },
   "p07": {
    "fit": 2.864,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "greenery",
      "phi": -1.225,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "thermal",
      "phi": 1.188,
      "obs": 1.0,
      "text": "it is comfortable to sit in"
     },
     {
      "f": "enclosure",
      "phi": 0.891,
      "obs": 0.75,
      "text": "it is enclosed"
     },
     {
      "f": "talk_ok",
      "phi": 0.669,
      "obs": 0.0,
      "text": "it is a silent room"
     }
    ]
   },
   "p08": {
    "fit": 3.2,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "greenery",
      "phi": -1.225,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "thermal",
      "phi": 1.188,
      "obs": 1.0,
      "text": "it is comfortable to sit in"
     },
     {
      "f": "enclosure",
      "phi": 0.891,
      "obs": 0.75,
      "text": "it is enclosed"
     },
     {
      "f": "talk_ok",
      "phi": 0.669,
      "obs": 0.0,
      "text": "it is a silent room"
     }
    ]
   },
   "p11": {
    "fit": -0.257,
    "slot": "weekend midday",
    "why": [
     {
      "f": "seat_comfort",
      "phi": 0.812,
      "obs": 0.75,
      "text": "the seating is comfortable for a long sit"
     },
     {
      "f": "noise_var",
      "phi": -0.627,
      "obs": 0.76,
      "text": "the noise comes in bursts"
     },
     {
      "f": "thermal",
      "phi": 0.551,
      "obs": 0.75,
      "text": "it is comfortable to sit in"
     },
     {
      "f": "greenery",
      "phi": -0.518,
      "obs": 0.25,
      "text": "there is nothing green in view"
     }
    ]
   },
   "p13": {
    "fit": 0.768,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.094,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "greenery",
      "phi": -0.518,
      "obs": 0.25,
      "text": "there is nothing green in view"
     },
     {
      "f": "noise",
      "phi": 0.417,
      "obs": 0.29,
      "text": "it is quiet"
     },
     {
      "f": "seat_comfort",
      "phi": -0.386,
      "obs": 0.25,
      "text": "the seating is hard or absent"
     }
    ]
   },
   "p14": {
    "fit": 2.405,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.094,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.397,
      "obs": 0.26,
      "text": "it is quiet"
     },
     {
      "f": "enclosure",
      "phi": 0.293,
      "obs": 0.5,
      "text": "it is open on all sides"
     },
     {
      "f": "privacy",
      "phi": 0.271,
      "obs": 0.75,
      "text": "nobody passes behind you"
     }
    ]
   },
   "p15": {
    "fit": -2.035,
    "slot": "weekend midday",
    "why": [
     {
      "f": "greenery",
      "phi": -1.225,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "noise_var",
      "phi": -0.72,
      "obs": 0.8,
      "text": "the noise comes in bursts"
     },
     {
      "f": "daylight",
      "phi": -0.405,
      "obs": 0.5,
      "text": "there is no real daylight"
     },
     {
      "f": "seat_comfort",
      "phi": -0.386,
      "obs": 0.25,
      "text": "the seating is hard or absent"
     }
    ]
   },
   "p16": {
    "fit": 4.487,
    "slot": "weekend midday",
    "why": [
     {
      "f": "seat_comfort",
      "phi": 1.41,
      "obs": 1.0,
      "text": "the seating is comfortable for a long sit"
     },
     {
      "f": "daylight",
      "phi": 1.094,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "enclosure",
      "phi": 0.891,
      "obs": 0.75,
      "text": "it is enclosed"
     },
     {
      "f": "privacy",
      "phi": 0.602,
      "obs": 1.0,
      "text": "nobody passes behind you"
     }
    ]
   },
   "p18": {
    "fit": 0.733,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "daylight",
      "phi": 1.094,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "thermal",
      "phi": 0.551,
      "obs": 0.75,
      "text": "it is comfortable to sit in"
     },
     {
      "f": "greenery",
      "phi": -0.518,
      "obs": 0.25,
      "text": "there is nothing green in view"
     },
     {
      "f": "noise",
      "phi": 0.393,
      "obs": 0.4,
      "text": "it is quiet"
     }
    ]
   },
   "p21": {
    "fit": 2.494,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.094,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.301,
      "obs": 0.2,
      "text": "it is quiet"
     },
     {
      "f": "enclosure",
      "phi": 0.293,
      "obs": 0.5,
      "text": "it is open on all sides"
     },
     {
      "f": "privacy",
      "phi": 0.271,
      "obs": 0.75,
      "text": "nobody passes behind you"
     }
    ]
   },
   "p22": {
    "fit": 0.964,
    "slot": "weekend midday",
    "why": [
     {
      "f": "greenery",
      "phi": 1.602,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "daylight",
      "phi": 1.094,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "enclosure",
      "phi": -0.904,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "privacy",
      "phi": -0.392,
      "obs": 0.25,
      "text": "you are exposed to foot traffic"
     }
    ]
   },
   "p23": {
    "fit": 1.516,
    "slot": "weekend midday",
    "why": [
     {
      "f": "greenery",
      "phi": 1.602,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "daylight",
      "phi": 1.094,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "enclosure",
      "phi": -0.904,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "seat_comfort",
      "phi": -0.386,
      "obs": 0.25,
      "text": "the seating is hard or absent"
     }
    ]
   },
   "p24": {
    "fit": 1.516,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "greenery",
      "phi": 1.602,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "daylight",
      "phi": -1.47,
      "obs": 0.25,
      "text": "there is no real daylight"
     },
     {
      "f": "privacy",
      "phi": 0.602,
      "obs": 1.0,
      "text": "nobody passes behind you"
     },
     {
      "f": "noise_var",
      "phi": 0.494,
      "obs": 0.38,
      "text": "the sound is steady rather than sudden"
     }
    ]
   },
   "p25": {
    "fit": 4.114,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "greenery",
      "phi": 1.602,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "noise_var",
      "phi": 0.956,
      "obs": 0.22,
      "text": "the sound is steady rather than sudden"
     },
     {
      "f": "thermal",
      "phi": 0.551,
      "obs": 0.75,
      "text": "it is comfortable to sit in"
     },
     {
      "f": "daylight",
      "phi": 0.451,
      "obs": 0.75,
      "text": "there is daylight where you would sit"
     }
    ]
   },
   "p26": {
    "fit": 3.015,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "daylight",
      "phi": 1.094,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "enclosure",
      "phi": -0.904,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "greenery",
      "phi": 0.895,
      "obs": 0.75,
      "text": "there is planting in view"
     },
     {
      "f": "privacy",
      "phi": 0.602,
      "obs": 1.0,
      "text": "nobody passes behind you"
     }
    ]
   },
   "p27": {
    "fit": 1.594,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "greenery",
      "phi": 1.602,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "daylight",
      "phi": 1.094,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "enclosure",
      "phi": -0.904,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "thermal",
      "phi": 0.551,
      "obs": 0.75,
      "text": "it is comfortable to sit in"
     }
    ]
   },
   "p30": {
    "fit": -1.726,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.094,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "enclosure",
      "phi": -0.904,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "noise_var",
      "phi": -0.581,
      "obs": 0.75,
      "text": "the noise comes in bursts"
     },
     {
      "f": "greenery",
      "phi": -0.518,
      "obs": 0.25,
      "text": "there is nothing green in view"
     }
    ]
   },
   "p31": {
    "fit": -1.192,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "daylight",
      "phi": 1.094,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "enclosure",
      "phi": -0.904,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "thermal",
      "phi": 0.551,
      "obs": 0.75,
      "text": "it is comfortable to sit in"
     },
     {
      "f": "greenery",
      "phi": -0.518,
      "obs": 0.25,
      "text": "there is nothing green in view"
     }
    ]
   },
   "p32": {
    "fit": 2.336,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "daylight",
      "phi": 1.094,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "enclosure",
      "phi": -0.904,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "privacy",
      "phi": 0.602,
      "obs": 1.0,
      "text": "nobody passes behind you"
     },
     {
      "f": "thermal",
      "phi": 0.551,
      "obs": 0.75,
      "text": "it is comfortable to sit in"
     }
    ]
   },
   "p33": {
    "fit": 1.487,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "daylight",
      "phi": 1.094,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "enclosure",
      "phi": -0.904,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "greenery",
      "phi": 0.895,
      "obs": 0.75,
      "text": "there is planting in view"
     },
     {
      "f": "thermal",
      "phi": 0.551,
      "obs": 0.75,
      "text": "it is comfortable to sit in"
     }
    ]
   },
   "p34": {
    "fit": -3.918,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.094,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "enclosure",
      "phi": -0.904,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "noise_var",
      "phi": -0.812,
      "obs": 0.83,
      "text": "the noise comes in bursts"
     },
     {
      "f": "privacy",
      "phi": -0.723,
      "obs": 0.0,
      "text": "you are exposed to foot traffic"
     }
    ]
   },
   "p35": {
    "fit": -3.291,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.094,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "enclosure",
      "phi": -0.904,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "privacy",
      "phi": -0.723,
      "obs": 0.0,
      "text": "you are exposed to foot traffic"
     },
     {
      "f": "noise_var",
      "phi": -0.616,
      "obs": 0.76,
      "text": "the noise comes in bursts"
     }
    ]
   },
   "p37": {
    "fit": 2.537,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.094,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.367,
      "obs": 0.24,
      "text": "it is quiet"
     },
     {
      "f": "enclosure",
      "phi": 0.293,
      "obs": 0.5,
      "text": "it is open on all sides"
     },
     {
      "f": "privacy",
      "phi": 0.271,
      "obs": 0.75,
      "text": "nobody passes behind you"
     }
    ]
   },
   "p38": {
    "fit": 2.778,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "greenery",
      "phi": 0.895,
      "obs": 0.75,
      "text": "there is planting in view"
     },
     {
      "f": "privacy",
      "phi": 0.602,
      "obs": 1.0,
      "text": "nobody passes behind you"
     },
     {
      "f": "thermal",
      "phi": 0.551,
      "obs": 0.75,
      "text": "it is comfortable to sit in"
     },
     {
      "f": "daylight",
      "phi": 0.451,
      "obs": 0.75,
      "text": "there is daylight where you would sit"
     }
    ]
   },
   "p39": {
    "fit": 2.723,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "thermal",
      "phi": 1.188,
      "obs": 1.0,
      "text": "it is comfortable to sit in"
     },
     {
      "f": "daylight",
      "phi": 1.094,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.425,
      "obs": 0.3,
      "text": "it is quiet"
     },
     {
      "f": "enclosure",
      "phi": -0.306,
      "obs": 0.25,
      "text": "it is open on all sides"
     }
    ]
   }
  }
 },
 {
  "id": "talk",
  "prompt": "i want to think out loud with a friend",
  "reply": "<b>strawberry creek north fork</b>, weekday afternoon. there is planting in view, and it is quiet.",
  "top": "p25",
  "ranked": [
   "p25",
   "p27",
   "p23",
   "p22",
   "p37",
   "p16",
   "p14",
   "p21",
   "p39",
   "p33",
   "p11",
   "p26",
   "p38",
   "p31",
   "p32",
   "p30",
   "p24",
   "p18",
   "p13",
   "p35",
   "p34",
   "p01",
   "p07",
   "p06",
   "p08",
   "p03",
   "p15",
   "p04"
  ],
  "places": {
   "p01": {
    "fit": -0.995,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "greenery",
      "phi": -1.65,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "talk_ok",
      "phi": -1.18,
      "obs": 0.0,
      "text": "it is a silent room"
     },
     {
      "f": "noise_var",
      "phi": 0.468,
      "obs": 0.35,
      "text": "the sound is steady rather than sudden"
     },
     {
      "f": "enclosure",
      "phi": 0.416,
      "obs": 0.75,
      "text": "it is enclosed"
     }
    ]
   },
   "p03": {
    "fit": -2.119,
    "slot": "weekday midday",
    "why": [
     {
      "f": "greenery",
      "phi": -1.65,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "talk_ok",
      "phi": -1.18,
      "obs": 0.0,
      "text": "it is a silent room"
     },
     {
      "f": "daylight",
      "phi": -1.155,
      "obs": 0.25,
      "text": "there is no real daylight"
     },
     {
      "f": "seat_comfort",
      "phi": 0.954,
      "obs": 1.0,
      "text": "the seating is comfortable for a long sit"
     }
    ]
   },
   "p04": {
    "fit": -3.823,
    "slot": "weekday midday",
    "why": [
     {
      "f": "daylight",
      "phi": -2.139,
      "obs": 0.0,
      "text": "there is no real daylight"
     },
     {
      "f": "greenery",
      "phi": -1.65,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "talk_ok",
      "phi": -1.18,
      "obs": 0.0,
      "text": "it is a silent room"
     },
     {
      "f": "noise",
      "phi": 0.753,
      "obs": 0.38,
      "text": "it is quiet"
     }
    ]
   },
   "p06": {
    "fit": -1.92,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "greenery",
      "phi": -1.65,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "talk_ok",
      "phi": -1.18,
      "obs": 0.0,
      "text": "it is a silent room"
     },
     {
      "f": "crowding",
      "phi": -0.688,
      "obs": 0.87,
      "text": "it is busy at that hour"
     },
     {
      "f": "noise",
      "phi": 0.492,
      "obs": 0.27,
      "text": "it is quiet"
     }
    ]
   },
   "p07": {
    "fit": -0.999,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "greenery",
      "phi": -1.65,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "talk_ok",
      "phi": -1.18,
      "obs": 0.0,
      "text": "it is a silent room"
     },
     {
      "f": "enclosure",
      "phi": 0.416,
      "obs": 0.75,
      "text": "it is enclosed"
     },
     {
      "f": "noise",
      "phi": 0.404,
      "obs": 0.25,
      "text": "it is quiet"
     }
    ]
   },
   "p08": {
    "fit": -2.007,
    "slot": "weekday midday",
    "why": [
     {
      "f": "greenery",
      "phi": -1.65,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "talk_ok",
      "phi": -1.18,
      "obs": 0.0,
      "text": "it is a silent room"
     },
     {
      "f": "noise",
      "phi": -0.811,
      "obs": 0.05,
      "text": "it is quiet"
     },
     {
      "f": "noise_var",
      "phi": 0.584,
      "obs": 0.3,
      "text": "the sound is steady rather than sudden"
     }
    ]
   },
   "p11": {
    "fit": 1.576,
    "slot": "weekend midday",
    "why": [
     {
      "f": "talk_ok",
      "phi": 0.902,
      "obs": 1.0,
      "text": "talking is normal there"
     },
     {
      "f": "greenery",
      "phi": -0.698,
      "obs": 0.25,
      "text": "there is nothing green in view"
     },
     {
      "f": "noise",
      "phi": 0.679,
      "obs": 0.57,
      "text": "it is loud"
     },
     {
      "f": "seat_comfort",
      "phi": 0.549,
      "obs": 0.75,
      "text": "the seating is comfortable for a long sit"
     }
    ]
   },
   "p13": {
    "fit": 0.506,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 0.86,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "greenery",
      "phi": -0.698,
      "obs": 0.25,
      "text": "there is nothing green in view"
     },
     {
      "f": "noise",
      "phi": 0.536,
      "obs": 0.29,
      "text": "it is quiet"
     },
     {
      "f": "crowding",
      "phi": 0.262,
      "obs": 0.16,
      "text": "it is nearly empty at that hour"
     }
    ]
   },
   "p14": {
    "fit": 2.442,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "daylight",
      "phi": 0.86,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.798,
      "obs": 0.41,
      "text": "it is quiet"
     },
     {
      "f": "talk_ok",
      "phi": 0.382,
      "obs": 0.75,
      "text": "talking is normal there"
     },
     {
      "f": "crowding",
      "phi": -0.262,
      "obs": 0.55,
      "text": "it is busy at that hour"
     }
    ]
   },
   "p15": {
    "fit": -2.239,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "greenery",
      "phi": -1.65,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "noise_var",
      "phi": -0.627,
      "obs": 0.81,
      "text": "the noise comes in bursts"
     },
     {
      "f": "noise",
      "phi": 0.57,
      "obs": 0.3,
      "text": "it is quiet"
     },
     {
      "f": "daylight",
      "phi": -0.312,
      "obs": 0.5,
      "text": "there is no real daylight"
     }
    ]
   },
   "p16": {
    "fit": 2.574,
    "slot": "weekday morning",
    "why": [
     {
      "f": "seat_comfort",
      "phi": 0.954,
      "obs": 1.0,
      "text": "the seating is comfortable for a long sit"
     },
     {
      "f": "daylight",
      "phi": 0.86,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "greenery",
      "phi": -0.698,
      "obs": 0.25,
      "text": "there is nothing green in view"
     },
     {
      "f": "noise",
      "phi": 0.613,
      "obs": 0.31,
      "text": "it is quiet"
     }
    ]
   },
   "p18": {
    "fit": 0.79,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "daylight",
      "phi": 0.86,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.783,
      "obs": 0.4,
      "text": "it is quiet"
     },
     {
      "f": "greenery",
      "phi": -0.698,
      "obs": 0.25,
      "text": "there is nothing green in view"
     },
     {
      "f": "seat_comfort",
      "phi": -0.261,
      "obs": 0.25,
      "text": "the seating is hard or absent"
     }
    ]
   },
   "p21": {
    "fit": 2.275,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "daylight",
      "phi": 0.86,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.803,
      "obs": 0.42,
      "text": "it is quiet"
     },
     {
      "f": "talk_ok",
      "phi": 0.382,
      "obs": 0.75,
      "text": "talking is normal there"
     },
     {
      "f": "crowding",
      "phi": -0.262,
      "obs": 0.55,
      "text": "it is busy at that hour"
     }
    ]
   },
   "p22": {
    "fit": 2.92,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "greenery",
      "phi": 2.158,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "crowding",
      "phi": -0.867,
      "obs": 1.0,
      "text": "it is busy at that hour"
     },
     {
      "f": "daylight",
      "phi": 0.86,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.709,
      "obs": 0.35,
      "text": "it is quiet"
     }
    ]
   },
   "p23": {
    "fit": 3.129,
    "slot": "weekday midday",
    "why": [
     {
      "f": "greenery",
      "phi": 2.158,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "daylight",
      "phi": 0.86,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.652,
      "obs": 0.32,
      "text": "it is quiet"
     },
     {
      "f": "enclosure",
      "phi": -0.422,
      "obs": 0.0,
      "text": "it is open on all sides"
     }
    ]
   },
   "p24": {
    "fit": 1.036,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "greenery",
      "phi": 2.158,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "daylight",
      "phi": -1.155,
      "obs": 0.25,
      "text": "there is no real daylight"
     },
     {
      "f": "noise_var",
      "phi": 0.411,
      "obs": 0.38,
      "text": "the sound is steady rather than sudden"
     },
     {
      "f": "seat_comfort",
      "phi": -0.261,
      "obs": 0.25,
      "text": "the seating is hard or absent"
     }
    ]
   },
   "p25": {
    "fit": 4.088,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "greenery",
      "phi": 2.158,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "noise",
      "phi": 0.81,
      "obs": 0.44,
      "text": "it is quiet"
     },
     {
      "f": "noise_var",
      "phi": 0.795,
      "obs": 0.22,
      "text": "the sound is steady rather than sudden"
     },
     {
      "f": "daylight",
      "phi": 0.36,
      "obs": 0.75,
      "text": "there is daylight where you would sit"
     }
    ]
   },
   "p26": {
    "fit": 1.573,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "greenery",
      "phi": 1.206,
      "obs": 0.75,
      "text": "there is planting in view"
     },
     {
      "f": "daylight",
      "phi": 0.86,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": -0.561,
      "obs": 0.09,
      "text": "it is quiet"
     },
     {
      "f": "crowding",
      "phi": 0.476,
      "obs": 0.0,
      "text": "it is nearly empty at that hour"
     }
    ]
   },
   "p27": {
    "fit": 3.445,
    "slot": "weekday midday",
    "why": [
     {
      "f": "greenery",
      "phi": 2.158,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "daylight",
      "phi": 0.86,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.743,
      "obs": 0.37,
      "text": "it is quiet"
     },
     {
      "f": "enclosure",
      "phi": -0.422,
      "obs": 0.0,
      "text": "it is open on all sides"
     }
    ]
   },
   "p30": {
    "fit": 1.079,
    "slot": "weekend midday",
    "why": [
     {
      "f": "talk_ok",
      "phi": 0.902,
      "obs": 1.0,
      "text": "talking is normal there"
     },
     {
      "f": "daylight",
      "phi": 0.86,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.791,
      "obs": 0.41,
      "text": "it is quiet"
     },
     {
      "f": "greenery",
      "phi": -0.698,
      "obs": 0.25,
      "text": "there is nothing green in view"
     }
    ]
   },
   "p31": {
    "fit": 1.378,
    "slot": "weekend midday",
    "why": [
     {
      "f": "talk_ok",
      "phi": 0.902,
      "obs": 1.0,
      "text": "talking is normal there"
     },
     {
      "f": "daylight",
      "phi": 0.86,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.736,
      "obs": 0.36,
      "text": "it is quiet"
     },
     {
      "f": "greenery",
      "phi": -0.698,
      "obs": 0.25,
      "text": "there is nothing green in view"
     }
    ]
   },
   "p32": {
    "fit": 1.355,
    "slot": "weekday midday",
    "why": [
     {
      "f": "daylight",
      "phi": 0.86,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "enclosure",
      "phi": -0.422,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "talk_ok",
      "phi": 0.382,
      "obs": 0.75,
      "text": "talking is normal there"
     },
     {
      "f": "crowding",
      "phi": 0.306,
      "obs": 0.13,
      "text": "it is nearly empty at that hour"
     }
    ]
   },
   "p33": {
    "fit": 1.894,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "greenery",
      "phi": 1.206,
      "obs": 0.75,
      "text": "there is planting in view"
     },
     {
      "f": "daylight",
      "phi": 0.86,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.477,
      "obs": 0.27,
      "text": "it is quiet"
     },
     {
      "f": "enclosure",
      "phi": -0.422,
      "obs": 0.0,
      "text": "it is open on all sides"
     }
    ]
   },
   "p34": {
    "fit": 0.005,
    "slot": "weekend midday",
    "why": [
     {
      "f": "talk_ok",
      "phi": 0.902,
      "obs": 1.0,
      "text": "talking is normal there"
     },
     {
      "f": "daylight",
      "phi": 0.86,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "greenery",
      "phi": -0.698,
      "obs": 0.25,
      "text": "there is nothing green in view"
     },
     {
      "f": "noise_var",
      "phi": -0.675,
      "obs": 0.83,
      "text": "the noise comes in bursts"
     }
    ]
   },
   "p35": {
    "fit": 0.447,
    "slot": "weekend midday",
    "why": [
     {
      "f": "talk_ok",
      "phi": 0.902,
      "obs": 1.0,
      "text": "talking is normal there"
     },
     {
      "f": "daylight",
      "phi": 0.86,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "greenery",
      "phi": -0.698,
      "obs": 0.25,
      "text": "there is nothing green in view"
     },
     {
      "f": "noise_var",
      "phi": -0.512,
      "obs": 0.76,
      "text": "the noise comes in bursts"
     }
    ]
   },
   "p37": {
    "fit": 2.633,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "daylight",
      "phi": 0.86,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.796,
      "obs": 0.41,
      "text": "it is quiet"
     },
     {
      "f": "talk_ok",
      "phi": 0.382,
      "obs": 0.75,
      "text": "talking is normal there"
     },
     {
      "f": "crowding",
      "phi": -0.262,
      "obs": 0.55,
      "text": "it is busy at that hour"
     }
    ]
   },
   "p38": {
    "fit": 1.553,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "greenery",
      "phi": 1.206,
      "obs": 0.75,
      "text": "there is planting in view"
     },
     {
      "f": "daylight",
      "phi": 0.36,
      "obs": 0.75,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "seat_comfort",
      "phi": -0.261,
      "obs": 0.25,
      "text": "the seating is hard or absent"
     },
     {
      "f": "crowding",
      "phi": 0.253,
      "obs": 0.17,
      "text": "it is nearly empty at that hour"
     }
    ]
   },
   "p39": {
    "fit": 2.173,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "daylight",
      "phi": 0.86,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.583,
      "obs": 0.3,
      "text": "it is quiet"
     },
     {
      "f": "talk_ok",
      "phi": 0.382,
      "obs": 0.75,
      "text": "talking is normal there"
     },
     {
      "f": "thermal",
      "phi": 0.294,
      "obs": 1.0,
      "text": "it is comfortable to sit in"
     }
    ]
   }
  }
 },
 {
  "id": "calm",
  "prompt": "i need to calm down before a meeting",
  "reply": "<b>strawberry creek north fork</b>, weekend midday. there is planting in view, and it is quiet.",
  "top": "p25",
  "ranked": [
   "p25",
   "p26",
   "p38",
   "p23",
   "p27",
   "p08",
   "p21",
   "p07",
   "p37",
   "p16",
   "p32",
   "p33",
   "p01",
   "p14",
   "p24",
   "p22",
   "p39",
   "p03",
   "p06",
   "p13",
   "p18",
   "p04",
   "p31",
   "p15",
   "p30",
   "p11",
   "p35",
   "p34"
  ],
  "places": {
   "p01": {
    "fit": 3.198,
    "slot": "weekend midday",
    "why": [
     {
      "f": "greenery",
      "phi": -1.517,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "complexity",
      "phi": 0.912,
      "obs": 0.0,
      "text": "there is little to look at"
     },
     {
      "f": "enclosure",
      "phi": 0.848,
      "obs": 0.75,
      "text": "it is enclosed"
     },
     {
      "f": "talk_ok",
      "phi": 0.832,
      "obs": 0.0,
      "text": "it is a silent room"
     }
    ]
   },
   "p03": {
    "fit": 2.419,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": -1.733,
      "obs": 0.25,
      "text": "there is no real daylight"
     },
     {
      "f": "greenery",
      "phi": -1.517,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "enclosure",
      "phi": 1.417,
      "obs": 1.0,
      "text": "it is enclosed"
     },
     {
      "f": "complexity",
      "phi": 0.912,
      "obs": 0.0,
      "text": "there is little to look at"
     }
    ]
   },
   "p04": {
    "fit": -0.515,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": -3.194,
      "obs": 0.0,
      "text": "there is no real daylight"
     },
     {
      "f": "greenery",
      "phi": -1.517,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "complexity",
      "phi": 0.912,
      "obs": 0.0,
      "text": "there is little to look at"
     },
     {
      "f": "enclosure",
      "phi": 0.848,
      "obs": 0.75,
      "text": "it is enclosed"
     }
    ]
   },
   "p06": {
    "fit": 1.692,
    "slot": "weekend midday",
    "why": [
     {
      "f": "greenery",
      "phi": -1.517,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "complexity",
      "phi": 0.912,
      "obs": 0.0,
      "text": "there is little to look at"
     },
     {
      "f": "enclosure",
      "phi": 0.848,
      "obs": 0.75,
      "text": "it is enclosed"
     },
     {
      "f": "talk_ok",
      "phi": 0.832,
      "obs": 0.0,
      "text": "it is a silent room"
     }
    ]
   },
   "p07": {
    "fit": 3.404,
    "slot": "weekend midday",
    "why": [
     {
      "f": "greenery",
      "phi": -1.517,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "complexity",
      "phi": 0.912,
      "obs": 0.0,
      "text": "there is little to look at"
     },
     {
      "f": "enclosure",
      "phi": 0.848,
      "obs": 0.75,
      "text": "it is enclosed"
     },
     {
      "f": "talk_ok",
      "phi": 0.832,
      "obs": 0.0,
      "text": "it is a silent room"
     }
    ]
   },
   "p08": {
    "fit": 3.563,
    "slot": "weekend midday",
    "why": [
     {
      "f": "greenery",
      "phi": -1.517,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "complexity",
      "phi": 0.912,
      "obs": 0.0,
      "text": "there is little to look at"
     },
     {
      "f": "enclosure",
      "phi": 0.848,
      "obs": 0.75,
      "text": "it is enclosed"
     },
     {
      "f": "talk_ok",
      "phi": 0.832,
      "obs": 0.0,
      "text": "it is a silent room"
     }
    ]
   },
   "p11": {
    "fit": -2.966,
    "slot": "weekend midday",
    "why": [
     {
      "f": "noise",
      "phi": -1.117,
      "obs": 0.57,
      "text": "it is loud"
     },
     {
      "f": "complexity",
      "phi": -0.971,
      "obs": 0.75,
      "text": "there is a lot competing for attention"
     },
     {
      "f": "greenery",
      "phi": -0.642,
      "obs": 0.25,
      "text": "there is nothing green in view"
     },
     {
      "f": "talk_ok",
      "phi": -0.636,
      "obs": 1.0,
      "text": "talking is normal there"
     }
    ]
   },
   "p13": {
    "fit": 1.552,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.29,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.75,
      "obs": 0.29,
      "text": "it is quiet"
     },
     {
      "f": "greenery",
      "phi": -0.642,
      "obs": 0.25,
      "text": "there is nothing green in view"
     },
     {
      "f": "crowding",
      "phi": 0.499,
      "obs": 0.16,
      "text": "it is nearly empty at that hour"
     }
    ]
   },
   "p14": {
    "fit": 3.163,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.29,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.795,
      "obs": 0.26,
      "text": "it is quiet"
     },
     {
      "f": "crowding",
      "phi": 0.396,
      "obs": 0.2,
      "text": "it is nearly empty at that hour"
     },
     {
      "f": "complexity",
      "phi": 0.285,
      "obs": 0.25,
      "text": "there is little to look at"
     }
    ]
   },
   "p15": {
    "fit": -1.044,
    "slot": "weekend midday",
    "why": [
     {
      "f": "greenery",
      "phi": -1.517,
      "obs": 0.0,
      "text": "there is nothing green in view"
     },
     {
      "f": "noise",
      "phi": 0.821,
      "obs": 0.17,
      "text": "it is quiet"
     },
     {
      "f": "noise_var",
      "phi": -0.714,
      "obs": 0.8,
      "text": "the noise comes in bursts"
     },
     {
      "f": "daylight",
      "phi": -0.476,
      "obs": 0.5,
      "text": "there is no real daylight"
     }
    ]
   },
   "p16": {
    "fit": 3.299,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.29,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "enclosure",
      "phi": 0.848,
      "obs": 0.75,
      "text": "it is enclosed"
     },
     {
      "f": "noise",
      "phi": 0.834,
      "obs": 0.23,
      "text": "it is quiet"
     },
     {
      "f": "greenery",
      "phi": -0.642,
      "obs": 0.25,
      "text": "there is nothing green in view"
     }
    ]
   },
   "p18": {
    "fit": 1.386,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.29,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.768,
      "obs": 0.28,
      "text": "it is quiet"
     },
     {
      "f": "crowding",
      "phi": 0.704,
      "obs": 0.08,
      "text": "it is nearly empty at that hour"
     },
     {
      "f": "greenery",
      "phi": -0.642,
      "obs": 0.25,
      "text": "there is nothing green in view"
     }
    ]
   },
   "p21": {
    "fit": 3.461,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.29,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.838,
      "obs": 0.2,
      "text": "it is quiet"
     },
     {
      "f": "crowding",
      "phi": 0.525,
      "obs": 0.15,
      "text": "it is nearly empty at that hour"
     },
     {
      "f": "complexity",
      "phi": 0.285,
      "obs": 0.25,
      "text": "there is little to look at"
     }
    ]
   },
   "p22": {
    "fit": 2.918,
    "slot": "weekend midday",
    "why": [
     {
      "f": "greenery",
      "phi": 1.983,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "daylight",
      "phi": 1.29,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "enclosure",
      "phi": -0.861,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "noise",
      "phi": 0.731,
      "obs": 0.12,
      "text": "it is quiet"
     }
    ]
   },
   "p23": {
    "fit": 4.01,
    "slot": "weekend midday",
    "why": [
     {
      "f": "greenery",
      "phi": 1.983,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "daylight",
      "phi": 1.29,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "complexity",
      "phi": 0.912,
      "obs": 0.0,
      "text": "there is little to look at"
     },
     {
      "f": "enclosure",
      "phi": -0.861,
      "obs": 0.0,
      "text": "it is open on all sides"
     }
    ]
   },
   "p24": {
    "fit": 2.97,
    "slot": "weekday morning",
    "why": [
     {
      "f": "greenery",
      "phi": 1.983,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "daylight",
      "phi": -1.733,
      "obs": 0.25,
      "text": "there is no real daylight"
     },
     {
      "f": "complexity",
      "phi": 0.912,
      "obs": 0.0,
      "text": "there is little to look at"
     },
     {
      "f": "crowding",
      "phi": 0.589,
      "obs": 0.12,
      "text": "it is nearly empty at that hour"
     }
    ]
   },
   "p25": {
    "fit": 5.061,
    "slot": "weekend midday",
    "why": [
     {
      "f": "greenery",
      "phi": 1.983,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "noise",
      "phi": 0.792,
      "obs": 0.26,
      "text": "it is quiet"
     },
     {
      "f": "noise_var",
      "phi": 0.72,
      "obs": 0.3,
      "text": "the sound is steady rather than sudden"
     },
     {
      "f": "crowding",
      "phi": 0.653,
      "obs": 0.1,
      "text": "it is nearly empty at that hour"
     }
    ]
   },
   "p26": {
    "fit": 4.803,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "daylight",
      "phi": 1.29,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "greenery",
      "phi": 1.108,
      "obs": 0.75,
      "text": "there is planting in view"
     },
     {
      "f": "complexity",
      "phi": 0.912,
      "obs": 0.0,
      "text": "there is little to look at"
     },
     {
      "f": "crowding",
      "phi": 0.909,
      "obs": 0.0,
      "text": "it is nearly empty at that hour"
     }
    ]
   },
   "p27": {
    "fit": 3.819,
    "slot": "weekend midday",
    "why": [
     {
      "f": "greenery",
      "phi": 1.983,
      "obs": 1.0,
      "text": "there is planting in view"
     },
     {
      "f": "daylight",
      "phi": 1.29,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "complexity",
      "phi": 0.912,
      "obs": 0.0,
      "text": "there is little to look at"
     },
     {
      "f": "enclosure",
      "phi": -0.861,
      "obs": 0.0,
      "text": "it is open on all sides"
     }
    ]
   },
   "p30": {
    "fit": -1.24,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.29,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "enclosure",
      "phi": -0.861,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "greenery",
      "phi": -0.642,
      "obs": 0.25,
      "text": "there is nothing green in view"
     },
     {
      "f": "talk_ok",
      "phi": -0.636,
      "obs": 1.0,
      "text": "talking is normal there"
     }
    ]
   },
   "p31": {
    "fit": -0.556,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.29,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "enclosure",
      "phi": -0.861,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "crowding",
      "phi": 0.695,
      "obs": 0.08,
      "text": "it is nearly empty at that hour"
     },
     {
      "f": "greenery",
      "phi": -0.642,
      "obs": 0.25,
      "text": "there is nothing green in view"
     }
    ]
   },
   "p32": {
    "fit": 3.251,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "daylight",
      "phi": 1.29,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "complexity",
      "phi": 0.912,
      "obs": 0.0,
      "text": "there is little to look at"
     },
     {
      "f": "enclosure",
      "phi": -0.861,
      "obs": 0.0,
      "text": "it is open on all sides"
     },
     {
      "f": "noise_var",
      "phi": 0.513,
      "obs": 0.37,
      "text": "the sound is steady rather than sudden"
     }
    ]
   },
   "p33": {
    "fit": 3.25,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.29,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "greenery",
      "phi": 1.108,
      "obs": 0.75,
      "text": "there is planting in view"
     },
     {
      "f": "complexity",
      "phi": 0.912,
      "obs": 0.0,
      "text": "there is little to look at"
     },
     {
      "f": "enclosure",
      "phi": -0.861,
      "obs": 0.0,
      "text": "it is open on all sides"
     }
    ]
   },
   "p34": {
    "fit": -6.418,
    "slot": "weekend midday",
    "why": [
     {
      "f": "noise",
      "phi": -2.457,
      "obs": 0.68,
      "text": "it is loud"
     },
     {
      "f": "complexity",
      "phi": -1.599,
      "obs": 1.0,
      "text": "there is a lot competing for attention"
     },
     {
      "f": "daylight",
      "phi": 1.29,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "enclosure",
      "phi": -0.861,
      "obs": 0.0,
      "text": "it is open on all sides"
     }
    ]
   },
   "p35": {
    "fit": -4.942,
    "slot": "weekend midday",
    "why": [
     {
      "f": "noise",
      "phi": -2.018,
      "obs": 0.65,
      "text": "it is loud"
     },
     {
      "f": "daylight",
      "phi": 1.29,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "complexity",
      "phi": -0.971,
      "obs": 0.75,
      "text": "there is a lot competing for attention"
     },
     {
      "f": "enclosure",
      "phi": -0.861,
      "obs": 0.0,
      "text": "it is open on all sides"
     }
    ]
   },
   "p37": {
    "fit": 3.353,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.29,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.824,
      "obs": 0.24,
      "text": "it is quiet"
     },
     {
      "f": "crowding",
      "phi": 0.396,
      "obs": 0.2,
      "text": "it is nearly empty at that hour"
     },
     {
      "f": "complexity",
      "phi": 0.285,
      "obs": 0.25,
      "text": "there is little to look at"
     }
    ]
   },
   "p38": {
    "fit": 4.076,
    "slot": "weekday afternoon",
    "why": [
     {
      "f": "greenery",
      "phi": 1.108,
      "obs": 0.75,
      "text": "there is planting in view"
     },
     {
      "f": "complexity",
      "phi": 0.912,
      "obs": 0.0,
      "text": "there is little to look at"
     },
     {
      "f": "noise",
      "phi": 0.836,
      "obs": 0.2,
      "text": "it is quiet"
     },
     {
      "f": "daylight",
      "phi": 0.533,
      "obs": 0.75,
      "text": "there is daylight where you would sit"
     }
    ]
   },
   "p39": {
    "fit": 2.822,
    "slot": "weekend midday",
    "why": [
     {
      "f": "daylight",
      "phi": 1.29,
      "obs": 1.0,
      "text": "there is daylight where you would sit"
     },
     {
      "f": "noise",
      "phi": 0.761,
      "obs": 0.14,
      "text": "it is quiet"
     },
     {
      "f": "crowding",
      "phi": 0.428,
      "obs": 0.19,
      "text": "it is nearly empty at that hour"
     },
     {
      "f": "enclosure",
      "phi": -0.291,
      "obs": 0.25,
      "text": "it is open on all sides"
     }
    ]
   }
  }
 }
];
